"""Add llm_response to evaluations

Revision ID: 8a5b2a06f8ec
Revises: 3c2b2689ca09
Create Date: 2025-07-30 00:57:07.843456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5b2a06f8ec'
down_revision: Union[str, Sequence[str], None] = '3c2b2689ca09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('llm_response', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'llm_response')
    # ### end Alembic commands ###
